### PR TITLE
Front end

### PR DESCRIPTION
**Pull request by davidou997**
Added initial React application with ProductBlock and ProductList components. Added local addition and deletion of products with dynamic list re-rendering.

Added UML Class Diagram for Deliverable 1

### CODE REVIEW

**Comment by yasinjaamac** [comment]
confirmed and resolved, works

**Comment by yusufjaamac** [comment]
resolved, everything works

**Comment by SamBaumann** [comment]
- [ x] Does this code change accomplish what it is supposed to do?
Elaborate: Basic product functionality up and running 

- [x ] Is the solution readable and easily understood?
Elaborate: Yes - code is clearly commented and legible

- [x ] Is the code free of logical error/bugs?
Elaborate: Behavior is as  expected

- [x ] Are errors and exceptions handled gracefully?
Elaborate: Yup

- [x ] If testing is possible, was it done?
Elaborate:  Yes - basic Cypress testing done

- [x ] Does the code require review from another developer before being committed?
Elaborate: Always review with 2 users!

**Comment by harrywinton5** [comment]
[ x] Does this code change accomplish what it is supposed to do?
Elaborate: Basic product functionality up and running

[x ] Is the solution readable and easily understood?
Elaborate: Yes - code is clearly commented and legible

[x ] Is the code free of logical error/bugs?
Elaborate: Behavior is as expected

[x ] Are errors and exceptions handled gracefully?
Elaborate: Yes

[x ] If testing is possible, was it done?
Elaborate: Yes

**Review by SamBaumann — APPROVED** [review]

**Pull request closed without merging**
